### ISSUE TITLE
'Couldn't sign you in' error is displayed

### ISSUE THREAD

**Issue by damosull** [adequatica/ui-testing-auth#1]
When I pull down the code & update the `test-user.ts` file with my google username & password, I'm getting this error message:

I ran the test in headed mode to see what was happening, the email is entered correctly, & the 'Next' button is clicked, but instead of the password field appearing, this is what appears:

<img width="776" alt="img" src="https://user-images.githubusercontent.com/31487026/224546353-c354aa02-d6a9-4473-bb5b-aff0db4f657e.PNG">

**Comment by adequatica** [comment]
Hi, it may be a problem with google account, please, try to use another one. 
It's a common problem for autotest https://stackoverflow.com/questions/60117232/selenium-google-login-block
